CREATE TABLE `jos_ierp_gatepass` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `billno` int NOT NULL,
  `state` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` int NOT NULL,
  `gid` int NOT NULL,
  `sysdate` datetime NOT NULL,
  `modifyby` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `modifydate` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `jobno` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `machine` int NOT NULL,
  `stkno` int NOT NULL,
  `date` date NOT NULL,
  `total` float NOT NULL,
  `yrid` int NOT NULL,
  `doc` int NOT NULL,
  `tolc` int NOT NULL,
  `fromlc` int NOT NULL,
  `indent` int NOT NULL,
  `status` int NOT NULL,
  `company` int NOT NULL,
  `handover` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `vehicle` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `completed` int NOT NULL DEFAULT '0',
  `ewaybill` int NOT NULL,
  `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `jos_ierp_gatepass_grid` (
  `id` int NOT NULL AUTO_INCREMENT,
  `billid` int NOT NULL,
  `stkno` int NOT NULL,
  `machine` int NOT NULL,
  `date` date NOT NULL,
  `propid` int NOT NULL,
  `serialno` varchar(200) NOT NULL,
  `hsncode` varchar(100) NOT NULL,
  `qty` int NOT NULL,
  `sec_qty` double NOT NULL,
  `thirdqty` double NOT NULL,
  `sec_width` double NOT NULL,
  `sec_height` double NOT NULL,
  `third_width` double NOT NULL,
  `third_height` double NOT NULL,
  `rate` float NOT NULL,
  `total` float NOT NULL,
  `batch` int NOT NULL,
  `description` text NOT NULL,
  `doc` int NOT NULL,
  `company` int NOT NULL,
  `yrid` int NOT NULL,
  `userid` int NOT NULL,
  `fromlc` int NOT NULL,
  `tolc` int NOT NULL,
  `uom` int NOT NULL,
  `status` int NOT NULL,
  `gid` int NOT NULL,
  `stock` int NOT NULL,
  `remark` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `date_idx` (`date`),
  KEY `gid_idx` (`gid`),
  KEY `serialno_idx` (`serialno`),
  KEY `yrid_idx` (`yrid`),
  KEY `doc_idx` (`doc`),
  KEY `propid_idx` (`propid`)
);